# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_input_task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, img


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1118, 756)
        Form.setStyleSheet("background colour :rgb(255, 255, 255)")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1131, 761))
        self.frame.setStyleSheet("background-color : rgb(255, 255, 255)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(480, 200, 151, 51))
        self.label_3.setStyleSheet("font-size: 20px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(480, 260, 401, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setStyleSheet("border : 0;\n"
"border-bottom: 1px solid;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setStyleSheet("border : 0;\n"
"border-bottom: 1px solid;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_3.setStyleSheet("border : 0;\n"
"border-bottom: 1px solid;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_4.setStyleSheet("border : 0;\n"
"border-bottom: 1px solid;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout.addWidget(self.lineEdit_4)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(480, 470, 93, 31))
        self.pushButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(17, 132, 255);\n"
"color:white;\n"
"font-size: 20px;\n"
"font-weight: 400;")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(470, 90, 151, 121))
        self.label_5.setStyleSheet("image: url(:/img/1.JPG);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(60, 160, 361, 451))
        self.label_6.setStyleSheet("image: url(:/img/Only 25k.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 470, 131, 28))
        self.pushButton_2.setStyleSheet("border: none;\n"
"text-decoration:underline;\n"
"font-size:15px;\n"
"color: #505050;")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "BELLYBELL SMD"))
        self.lineEdit.setText(_translate("Form", "Kasir Siang/Malam"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.lineEdit_2.setText(_translate("Form", "Customer"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "NIM"))
        self.lineEdit_3.setText(_translate("Form", "Masukan Pesanan"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "URL Github"))
        self.lineEdit_4.setText(_translate("Form", "Antrian"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Nama Lengkap"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText(_translate("Form", "Lihat Pesanan"))

if __name__ =="__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())